config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  resources :products do
    resources :reviews, only: [:show, :create, :destroy]
    resources :categories, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :products
  validates :name, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :users, through: :reviews
  has_and_belongs_to_many :categories


  validates :description, :name, presence: true
  validates :price_in_cents, numericality: {only_integer: true}

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates :comment, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_many :products, through: :reviews
  has_secure_password
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # def create
  # end

  def destroy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = if params[:search]
      Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
    else
      Product.all
    end

    @products = @products.order('products.created_at DESC').page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end
  end

  def new
    @product = Product.new
    @categories = @product.categories.build
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_product
  before_filter :ensure_logged_in, only: [:create, :destroy]

  def show
    @review = Review.find(params[:id])
  end

  def create

    # @review = Review.new(
    #   comment: params[:review][:comment],
    #   product_id: @product.id,
    #   user_id: current_user.id
    # )
    # alternative syntax

    @review = @product.reviews.build(review_params)
    @review.user = current_user
    respond_to do |format|
      if @review.save
        #redirect_to products_path, notice: "Review created sucessfully"
        format.html { redirect_to product_path(@product.id), notice: "Review added."}
        format.js {} # This will look for app/views/reviews/create.js.erb
      else
        format.html { render 'products/show', alert: 'There was an error.' }
        format.js {}
        #render 'products/show'
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to products_url, notice: "Signned up!"
    else
      render "new"
    end
  end

  def show
  end


  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <%= link_to "Add New Product", new_product_path %>
  </nav>

  <% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p>
  <% end %>

  <%= yield %>

  <p class="userinfo">
    <% if current_user %>
      Signed in as <%= current_user.name %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <%= link_to "Profile", user_path(current_user.id) %>
    <% else %>
      <%= link_to "Log_in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
    <% end %>
  </p>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <%= render partial: 'shared/flash', locals: { object: @product } %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price_in_cents %><br>
    <%= f.text_area :price_in_cents %>
  </div>

  <div class="field">
  <h2>Categories</h2>
    <%= f.fields_for :categories do |cat_form| %>
      <%= cat_form.label :name %>
      <%= cat_form.text_field :name %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<ul>
    <li>Product id: <%= link_to product.id, product_path(product.id) %> </li>
    <li>Product Name: <%= product.name %></li>
    <li>Product Description: <%= product.description %></li>
    <li>Product Price: <%= product.formatted_price %></li>
</ul>

app/views/products/_review_form_errors.html.erb
<% if @review.errors.present? %>
  <% @review.errors.full_messages.each do |error| %>
    <div class="alert">
      <%= error %>
    </div>
  <% end %>
<% end %>

app/views/products/_reviews.html.erb
<% #@product.reviews.order(created_at: :desc).each do |review| %>
  <div class="review">
    <% if review.user != nil %>
      <div class="poster">
        <em>by <%= review.user.email %></em>
        Added on: <%= review.created_at %>
      </div>
      <p class="comment">
        <%= review.comment %>
      </p>
    <% end %>
  </div>
<%# end %>

app/views/products/edit.html.erb
<h1>Products edit</h1>
<%= render 'form' %>
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<h1><small><%= page_entries_info @products %></small></h1>

<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search]%>
  <%= submit_tag "Search" %>
<% end %>

<div id="products">
  <%= render @products %>
</div>

<%= paginate @products %>

app/views/products/index.js.erb
//$('#products').html("<%= escape_javascript(render @products) %>");

<% if params[:search] && params[:page].nil? %>
  $('#products').html("<%= j(render @products) %>");
<% else %>
  $('#products').append('<%= j render(@products) %>');
<% end %>

$('.pagination').replaceWith('<%= j paginate(@products) %>');

app/views/products/new.html.erb
<h1>Products#new</h1>
<%= render 'form' %>
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Products</h1>
<%= link_to "back", :back %>

<ul>
  <li>Product Name: <%= @product.name %></li>
  <li>Product Description: <%= @product.description %></li>
  <li>Product price: <%= @product.formatted_price %></li>
</ul>

<h3>Categories</h3>
<% @product.categories.each do |category| %>
  <p>
    <%= category.name %>, &nbsp
  </p>
<% end %>

<% if current_user %>
  <h4>New Review</h4>
  <div id="review-form-errors">
    <%= render :partial => "/products/review_form_errors" %>
  </div>
  <%= form_for [@product, @review], remote: true do |f| %>
    <div class="field">
      <%= f.label :comment %><br>
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review. </p>
<% end %>

<h3>Reviews</h3>

<p>Reviews for <%= @product.name %></p>
<div id="review-list">
  <%= render @product.reviews.order(created_at: :asc) %>
</div>

<script type="text/javascript">
$(function(){
  $("#new_review")
    .on('ajax:beforeSend', function(){
      $("input[type='submit']")
        .val('Saving...')
        .attr('disabled', 'disabled')
    })
    .on('ajax:complete', function(){
      $("input[type='submit']")
        .val('Create Review')
        .removeAttr('disabled');
    });
});
</script>

app/views/products/show.js.erb
$('body').append("<%= escape_javascript(render @product) %>");

app/views/reviews/_review.html.erb
<div class="review">
  <% if review.user != nil %>
    <div class="poster">
      <em>by <%= review.user.email %></em>
      Added on: <%= review.created_at %>
    </div>
    <p class="comment">
      <%= review.comment %>
    </p>
  <% end %>
</div>

app/views/reviews/create.html.erb
<h1>Review#create</h1>
<p>Find me in app/views/review/create.html.erb</p>

app/views/reviews/create.js.erb
<% if @review.errors.present? %>
  $("#review-form-errors").html("<%= j (render(:partial => '/products/review_form_errors')) %>");
<% else %>
  $("review-form-errors").html("");
  $("#review-list .review:last-child").css("background-color", "");
  $("#review-list").append("<%= j (render @review) %>");
  $('html, body').animate({
        scrollTop: $("#review-list .review:last-child").offset().top
    }, 500, function(){
      $("#review-list .review:last-child").css("background-color", "yellow");
    });

  $("#new_review")[0].reset();
<% end %>

app/views/reviews/destroy.html.erb
<h1>Review#destroy</h1>
<p>Find me in app/views/review/destroy.html.erb</p>

app/views/reviews/show.html.erb
<h1>Review#show</h1>
<p>Find me in app/views/review/show.html.erb</p>

app/views/shared/_flash.html.erb
  <h2><%= pluralize(object.errors.count, "error") %>prohibited from being saved:</h2>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <%= render partial: 'shared/flash', locals: { object: @user } %>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Profile for <%= current_user.name %></h1>
<ul>
  <li>Created on: <%= current_user.created_at %></li>
  <li>Email: <%= current_user.email %></li>
</ul>